# Generated by Django 4.2.4 on 2023-09-04 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0002_resources"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resources",
            name="dept_id",
        ),
        migrations.RemoveField(
            model_name="resources",
            name="user_id",
        ),
    ]
