# Generated by Django 4.2.4 on 2023-09-04 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0003_remove_resources_dept_id_remove_resources_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="dept_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="resources.departments",
            ),
        ),
        migrations.AddField(
            model_name="resources",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
