# Generated by Django 4.2.4 on 2023-09-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0004_resources_dept_id_resources_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resources",
            name="dept_id",
        ),
        migrations.AlterField(
            model_name="resources",
            name="dept_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="resources.departments",
            ),
        ),
    ]
