# Generated by Django 4.2.4 on 2023-09-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0005_remove_resources_dept_id_alter_resources_dept_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("doctor_name", models.CharField(max_length=100)),
                ("doctor_specialization", models.TextField(max_length=1000)),
                (
                    "dept_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources.departments",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Appointments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("patient_name", models.CharField(max_length=100)),
                ("patient_email", models.EmailField(max_length=50)),
                ("patient_phone", models.CharField(max_length=50)),
                (
                    "doctor_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources.doctors",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
