# Generated by Django 4.2.4 on 2023-09-04 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0007_alter_departments_options_alter_doctors_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointments",
            options={"verbose_name_plural": "Appointments"},
        ),
    ]
