# Generated by Django 4.2.4 on 2023-09-04 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0008_alter_appointments_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resources",
            old_name="description",
            new_name="descriptions",
        ),
    ]
